"le caractère" = "het karakter"
"le défaut" = "het gebrek / de fout / het minpunt"
"le passe-temps" = "het tijdverdrijf"
"l'astuce (f)" = "het trucje"
"les coordonnées (f)" = "de gegevens"
"la qualité" = "de kwaliteit"
"asocial(e)" = "asociaal"
"aventureu(x)(se)" = "avontuurlijk"
"bavard(e)" = "babbelziek"
"brutal(e)" = "brutaal"
"déterminé(e)" = "vastberaden / kordaat"
"distrait(e)" = "verstrooid"
"énergique" = "energiek"
"honnête" = "eerlijk"
"intelligent(e)" = "intelligent / verstandig"
"naï(f)(ve)" = "naïef"
"nonchalant(e)" = "nonchalant"
"paresseu(x)(se)" = "lui"
"patient(e)" = "geduldig"
"prudent(e)" = "voorzichtig"
"réaliste" = "realistisch"
"sensible (à)" = "gevoelig (voor)"
"sévère" = "streng"
"sociable" = "sociaal"
"spontané(e)" = "spontaan"
"têtu(e)" = "koppig"
"timide" = "verlegen"
"avoir l'air" = "lijken"
"devenir" = "worden"
"être à la recherche de" = "op zoek zijn naar / zoeken"
"être en train de" = "bezig zijn met / aan het … zijn"
"le bâtiment" = "het gebouw"
"le distributeur automatique" = "de automaat"
"l'embouteillage (m)" = "de file"
"l'endroit (m)" = "de plaats"
"le guichet" = "het loket"
"l'itinéraire (m)" = "de reisweg"
"le panneau" = "het (verkeers)bord"
"le piéton" = "de voetganger"
"le poids lourd" = "de vrachtwagen"
"le quartier" = "de wijk"
"l'autoroute (f)" = "de autosnelweg"
"la bande" = "de rijstrook"
"la capitale" = "de hoofdstad"
"la commune" = "de gemeente"
"la correspondance" = "de aansluiting"
"la destination" = "de bestemming"
"la déviation" = "de omleiding"
"la distance" = "de afstand"
"la zone piétonne" = "de voetgangerszone"
"causer" = "veroorzaken"
"descendre de" = "uitstappen"
"monter dans" = "instappen"
"ralentir" = "vertragen"
"partager avec" = "delen met"
"se situer" = "zich bevinden"
"vérifier" = "controleren, nagaan"
"donner accès à" = "toegang geven tot"
"être pris dans un embouteillage" = "in een file staan"
"tenir au courant de" = "op de hoogte houden"
"tenir compte de" = "rekening houden met"
"alternatif, alternative" = "alternatief"
"obligatoire" = "verplicht"
