title = "Plant histology"
[definitions]
"cell membrane" = "The cell membrane is a thin, flexible barrier around a cell; composed of a lipid bilayer with proteins embedded in it."
"cell wall" = "The cell wall is a rigid structure that surrounds the cell membrane and provides support to the cell."
